name: Melon Ticket 알림

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  check-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Ticket
        uses: mooyoul/melon-ticket-actions@main
        with:
          product-id: 204755
          schedule-id: 100001
          seat-id: 1_0
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
